name: Terraform Destroy (nightly)
on:
  # schedule:
  #  - cron: "0 15 * * *"   # UTC 15:00 = 台灣時間 23:00
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.GHA_APPLY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: |
          terraform destroy -auto-approve -var="alert_email=${{ vars.ALERT_EMAIL }}" \
            -target=module.infra.aws_instance.control \
            -target=module.infra.aws_autoscaling_group.worker \
            -target=module.infra.aws_launch_template.worker \
            -target=module.infra.aws_eip.control
